version: "3.9"

services:
  db:
    image: postgres:17
    container_name: kcal_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data  # сохраняем данные между перезапусками
      - ./dump:/docker-entrypoint-initdb.d  # все SQL-скрипты из dump/ выполнятся при первом запуске

  app:
    build: .
    container_name: kcal_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"   # бэкенд доступен на http://localhost:8080 из Windows

volumes:
  db_data:
