BEGIN;

CREATE TABLE IF NOT EXISTS users
(
    password_hash VARCHAR(255),
    login VARCHAR(255),
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONSTRAINT users_login_unique UNIQUE (login)
    );


CREATE TABLE IF NOT EXISTS products
(
    name VARCHAR(255),
    kcal DOUBLE PRECISION,
    proteins DOUBLE PRECISION,
    fats DOUBLE PRECISION,
    carbohydrates DOUBLE PRECISION,
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS meals
(
    name VARCHAR(255),
    weight DOUBLE PRECISION,
    kcal DOUBLE PRECISION,
    proteins DOUBLE PRECISION,
    fats DOUBLE PRECISION,
    carbohydrates DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS products_aliases
(
    name VARCHAR(255),
    product_id INTEGER REFERENCES public.products,
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS measurements
(
    weight DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS trainings
(
    kcal DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id)
);

COMMIT;