BEGIN;

CREATE TABLE IF NOT EXISTS products
(
    name VARCHAR(255),
    kcal DOUBLE PRECISION,
    proteins DOUBLE PRECISION,
    fats DOUBLE PRECISION,
    carbohydrates DOUBLE PRECISION,
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS meals
(
    name VARCHAR(255),
    weight DOUBLE PRECISION,
    kcal DOUBLE PRECISION,
    proteins DOUBLE PRECISION,
    fats DOUBLE PRECISION,
    carbohydrates DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS products_aliases
(
    name
    VARCHAR(255),
    product_id INTEGER REFERENCES public.products,
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);


COMMIT;